<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="AWSSDK.S3" Version="4.0.103.3" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Data.Sqlite" Version="10.0.12" />
    <PackageVersion Include="xunit.v3" Version="4.0.1" />
  </ItemGroup>

</Project>
