<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Testing.Extensions.GitHubActionsReport" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\S3Harp.Server\S3Harp.Server.csproj" />
    <ProjectReference Include="..\S3Harp.TestSupport\S3Harp.TestSupport.csproj" />
  </ItemGroup>
</Project>
